web:
  build: .
  command: 'bash -c ''/app/user/dfhack'''
  working_dir: /app/user
  environment:
    PORT: 1235
  ports:
    - '1235:1235/udp'
  tty: true
  stdin_open: true
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 1235
  ports:
    - '1235:1235/udp'
  volumes:
    - '.:/app/working'
  tty: true
  stdin_open: true
