web:
  build: .
  command: 'bash -c ''/app/user/df_linux/dfhack'''
  working_dir: /app/user/df_linux
  environment:
    PORT: 1235
  ports:
    - '1235:1235/udp'
  tty: true
  stdin_open: false
shell:
  build: .
  command: bash
  working_dir: /app/user/df_linux
  environment:
    PORT: 1235
  ports:
    - '1235:1235/udp'
  volumes:
    - '.:/app/user/df_linux'
  tty: true
  stdin_open: true
